/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package polime.app.qlsv1.ui;

import javax.swing.ImageIcon;
import javax.swing.JFrame;
import polime.app.qlsv1.ui.infor;
import polime.app.qlsv1.ui.loginJDialog;
/**
 *
 * @author Admin
 */
public class mainframe extends javax.swing.JFrame {
    private infor minfor;
    private student mstudent;
    private GPA mgpGpa;
    /**
     * Creates new form mainframe
     */
    public mainframe() {
        initComponents();
        setLocationRelativeTo(null);
        setExtendedState(getExtendedState() | JFrame.MAXIMIZED_BOTH);
        loginJDialog lg=new loginJDialog(this,true);
        lg.setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jToolBar1 = new javax.swing.JToolBar();
        jButton1 = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JToolBar.Separator();
        jSeparator2 = new javax.swing.JToolBar.Separator();
        btsinhvien = new javax.swing.JButton();
        jSeparator4 = new javax.swing.JToolBar.Separator();
        btdiem = new javax.swing.JButton();
        jSeparator3 = new javax.swing.JToolBar.Separator();
        btthongtin = new javax.swing.JButton();
        tablepanel = new javax.swing.JTabbedPane();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        menusinhvien = new javax.swing.JMenuItem();
        menubangdiem = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        menuiff = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jToolBar1.setRollover(true);

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/polime/app/qlsv1/logout-icon-32.png"))); // NOI18N
        jButton1.setText("Đăng xuất");
        jButton1.setFocusable(false);
        jButton1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton1.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jToolBar1.add(jButton1);
        jToolBar1.add(jSeparator1);
        jToolBar1.add(jSeparator2);

        btsinhvien.setIcon(new javax.swing.ImageIcon(getClass().getResource("/polime/app/qlsv1/10207-man-student-light-skin-tone-icon-24.png"))); // NOI18N
        btsinhvien.setText("Quản lý học sinh");
        btsinhvien.setFocusable(false);
        btsinhvien.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btsinhvien.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btsinhvien.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btsinhvienActionPerformed(evt);
            }
        });
        jToolBar1.add(btsinhvien);
        jToolBar1.add(jSeparator4);

        btdiem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/polime/app/qlsv1/Actions-view-choose-icon-24.png"))); // NOI18N
        btdiem.setText("Quản lý bảng điểm");
        btdiem.setFocusable(false);
        btdiem.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btdiem.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btdiem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btdiemActionPerformed(evt);
            }
        });
        jToolBar1.add(btdiem);
        jToolBar1.add(jSeparator3);

        btthongtin.setIcon(new javax.swing.ImageIcon(getClass().getResource("/polime/app/qlsv1/Actions-help-about-icon-32.png"))); // NOI18N
        btthongtin.setText("Thông tin");
        btthongtin.setFocusable(false);
        btthongtin.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btthongtin.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btthongtin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btthongtinActionPerformed(evt);
            }
        });
        jToolBar1.add(btthongtin);

        getContentPane().add(jToolBar1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 530, 70));
        getContentPane().add(tablepanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 80, 510, 470));

        jMenu1.setText("Hệ thống");

        jMenuItem1.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_C, java.awt.event.InputEvent.ALT_DOWN_MASK));
        jMenuItem1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/polime/app/qlsv1/Login-icon-16.png"))); // NOI18N
        jMenuItem1.setText("Đăng xuất");
        jMenu1.add(jMenuItem1);

        jMenuItem2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/polime/app/qlsv1/Actions-edit-delete-icon-16.png"))); // NOI18N
        jMenuItem2.setText("Thoát");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem2);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Quản lý");

        menusinhvien.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_4, java.awt.event.InputEvent.SHIFT_DOWN_MASK));
        menusinhvien.setIcon(new javax.swing.ImageIcon(getClass().getResource("/polime/app/qlsv1/10207-man-student-light-skin-tone-icon-16.png"))); // NOI18N
        menusinhvien.setText("Quản lý học sinh");
        menusinhvien.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menusinhvienActionPerformed(evt);
            }
        });
        jMenu2.add(menusinhvien);

        menubangdiem.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_7, java.awt.event.InputEvent.SHIFT_DOWN_MASK));
        menubangdiem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/polime/app/qlsv1/Actions-view-choose-icon-24.png"))); // NOI18N
        menubangdiem.setText("Quản lý bảng điểm");
        menubangdiem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menubangdiemActionPerformed(evt);
            }
        });
        jMenu2.add(menubangdiem);

        jMenuBar1.add(jMenu2);

        jMenu3.setText("Trợ giúp");

        menuiff.setIcon(new javax.swing.ImageIcon(getClass().getResource("/polime/app/qlsv1/Actions-help-about-icon-16.png"))); // NOI18N
        menuiff.setText("Thông tin");
        menuiff.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuiffActionPerformed(evt);
            }
        });
        jMenu3.add(menuiff);

        jMenuBar1.add(jMenu3);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void menusinhvienActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menusinhvienActionPerformed
        if(mstudent==null){
            mstudent =new student();
            ImageIcon icon = new ImageIcon(getClass().getResource("/polime/app/qlsv1/10207-man-student-light-skin-tone-icon-24.png"));
            tablepanel.addTab("Quản lý học sinh",icon,mstudent,"Quản lý học sinh");
            }
        tablepanel.setSelectedComponent(mstudent);
    }//GEN-LAST:event_menusinhvienActionPerformed

    private void menubangdiemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menubangdiemActionPerformed
        if(mgpGpa==null){
            mgpGpa = new GPA();
            ImageIcon icon = new ImageIcon(getClass().getResource("/polime/app/qlsv1/Actions-view-choose-icon-24.png"));
            tablepanel.addTab("Quản lý bảng điểm",icon,mgpGpa,"Quản lý bảng điểm");
            }
        tablepanel.setSelectedComponent(mgpGpa);   
    }//GEN-LAST:event_menubangdiemActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        System.exit(0);
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void btsinhvienActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btsinhvienActionPerformed
            if(mstudent==null){
            mstudent =new student();
            ImageIcon icon = new ImageIcon(getClass().getResource("/polime/app/qlsv1/10207-man-student-light-skin-tone-icon-24.png"));
            tablepanel.addTab("Quản lý học sinh",icon,mstudent,"Quản lý học sinh");
            }
        tablepanel.setSelectedComponent(mstudent);
    }//GEN-LAST:event_btsinhvienActionPerformed

    private void btdiemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btdiemActionPerformed
        if(mgpGpa==null){
            mgpGpa = new GPA();
            ImageIcon icon = new ImageIcon(getClass().getResource("/polime/app/qlsv1/Actions-view-choose-icon-24.png"));
            tablepanel.addTab("Quản lý bảng điểm",icon,mgpGpa,"Quản lý bảng điểm");
            }
        tablepanel.setSelectedComponent(mgpGpa);   
    }//GEN-LAST:event_btdiemActionPerformed

    private void btthongtinActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btthongtinActionPerformed
        infor i=new infor(this,true);
        i.setVisible(true);
    }//GEN-LAST:event_btthongtinActionPerformed

    private void menuiffActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuiffActionPerformed
        infor i=new infor(this,true);
        i.setVisible(true);
    }//GEN-LAST:event_menuiffActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(mainframe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(mainframe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(mainframe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(mainframe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new mainframe().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btdiem;
    private javax.swing.JButton btsinhvien;
    private javax.swing.JButton btthongtin;
    private javax.swing.JButton jButton1;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JToolBar.Separator jSeparator1;
    private javax.swing.JToolBar.Separator jSeparator2;
    private javax.swing.JToolBar.Separator jSeparator3;
    private javax.swing.JToolBar.Separator jSeparator4;
    private javax.swing.JToolBar jToolBar1;
    private javax.swing.JMenuItem menubangdiem;
    private javax.swing.JMenuItem menuiff;
    private javax.swing.JMenuItem menusinhvien;
    private javax.swing.JTabbedPane tablepanel;
    // End of variables declaration//GEN-END:variables
}
