/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package polime.app.qlsv1.ui;

import javax.swing.JOptionPane;
import polime.app.qlsv1.helper.Value;
import polime.app.qlsv1.helper.Showmesager;
import polime.app.qlsv1.model.hocsinh;
import polime.app.qlsv1.dao.sinhviendao;

/**
 *
 * @author Admin
 */
public class student extends javax.swing.JPanel {
    
    private mainframe parent;
    
    /**
     * Creates new form student
     */
    public student() {
        initComponents();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel2 = new javax.swing.JLabel();
        txtmasosinhvien = new javax.swing.JTextField();
        btnhapmoi = new javax.swing.JButton();
        txthoten = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        rdinam = new javax.swing.JRadioButton();
        txtsdt = new javax.swing.JTextField();
        txtemail = new javax.swing.JTextField();
        rdonu = new javax.swing.JRadioButton();
        btthem = new javax.swing.JButton();
        btsua = new javax.swing.JButton();
        btxoa = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtarea = new javax.swing.JTextArea();
        jLabel7 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/polime/app/qlsv1/10207-man-student-light-skin-tone-icon-24.png"))); // NOI18N
        jLabel1.setText("Sinh viên");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 100, -1));
        add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 31, 518, 10));

        jLabel2.setText("Mã số sinh viên");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 52, -1, -1));
        add(txtmasosinhvien, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 50, 220, -1));

        btnhapmoi.setIcon(new javax.swing.ImageIcon(getClass().getResource("/polime/app/qlsv1/new-icon-16.png"))); // NOI18N
        btnhapmoi.setText("Nhập mới");
        btnhapmoi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnhapmoiActionPerformed(evt);
            }
        });
        add(btnhapmoi, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 70, 110, 30));
        add(txthoten, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 90, 220, -1));

        jLabel3.setText("Họ & tên");
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 90, -1, -1));

        jLabel6.setText("Email");
        add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 130, -1, -1));

        jLabel5.setText("SDT");
        add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 170, -1, -1));

        jLabel4.setText("Giới tính");
        add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 210, -1, -1));

        buttonGroup1.add(rdinam);
        rdinam.setText("Nam");
        add(rdinam, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 200, -1, -1));
        add(txtsdt, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 170, 220, -1));
        add(txtemail, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 130, 220, -1));

        buttonGroup1.add(rdonu);
        rdonu.setText("Nữ");
        add(rdonu, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 200, -1, -1));

        btthem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/polime/app/qlsv1/Save-icon.png"))); // NOI18N
        btthem.setText("Thêm");
        btthem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btthemActionPerformed(evt);
            }
        });
        add(btthem, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 120, 110, 30));

        btsua.setIcon(new javax.swing.ImageIcon(getClass().getResource("/polime/app/qlsv1/Actions-document-edit-icon-16.png"))); // NOI18N
        btsua.setText("Sửa");
        btsua.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btsuaActionPerformed(evt);
            }
        });
        add(btsua, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 180, 110, 30));

        btxoa.setIcon(new javax.swing.ImageIcon(getClass().getResource("/polime/app/qlsv1/Actions-edit-delete-icon-16.png"))); // NOI18N
        btxoa.setText("Xóa");
        btxoa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btxoaActionPerformed(evt);
            }
        });
        add(btxoa, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 230, 110, 30));

        txtarea.setColumns(20);
        txtarea.setRows(5);
        jScrollPane1.setViewportView(txtarea);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 230, 251, -1));

        jLabel7.setText("Địa chỉ");
        add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 250, 40, -1));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(jTable1);

        add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 340, 440, 100));
    }// </editor-fold>//GEN-END:initComponents

    private void btthemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btthemActionPerformed
        StringBuilder sb = new StringBuilder();
        Value.vl(txtmasosinhvien, sb, "Mã số sinh viên không được để trống !");
        Value.vl(txthoten, sb, "Họ và tên sinh viên không được để trống !");
        if (sb.length() > 0) {
            Showmesager.showerormess(parent, sb.toString(), "Lỗi");
            return;
        }
        try {
            hocsinh sv = new hocsinh();
            sv.setMaSinhVien(txtmasosinhvien.getText());
            sv.setHoTen(txthoten.getText());
            sv.setEmail(txtemail.getText());
            sv.setSDT(txtsdt.getText());
            sv.setGioiTinh(rdinam.isSelected() ? 1 : 0);
            sv.setDiaChi(txtarea.getText());
            sinhviendao dao = new sinhviendao();
            if (dao.insert(sv)) {
                Showmesager.showmess(parent, "Sinh viên đã được lưu /(^0^)/", "Thông báo");
            } else {
                Showmesager.showcomfirmess(parent, "Sinh viên không lưu được do lỗi kỹ thuật =(", "Cảnh báo !!!");
            }
        } catch (Exception e2) {
            e2.printStackTrace();
            Showmesager.showerormess(parent, e2.getMessage(), "Lỗi");
        }
    }//GEN-LAST:event_btthemActionPerformed

    private void btxoaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btxoaActionPerformed
        StringBuilder sb = new StringBuilder();
        Value.vl(txtmasosinhvien, sb, "Mã số sinh viên không được để trống !");
        if (sb.length() > 0) {
            Showmesager.showerormess(parent, sb.toString(), "Lỗi");
            return;
        }
        if (Showmesager.showcomfirmess(parent, "Bạn có muốn xóa sinh viên không ",
                "Hỏi") == JOptionPane.NO_OPTION) {
            return;
        }
        try {
            sinhviendao dao = new sinhviendao();
            if (dao.delete(txtmasosinhvien.getText())) {
                Showmesager.showcomfirmess(parent, "Sinh viên không xóa được do lỗi kỹ thuật +(",
                        "Cảnh báo !!!");
            } else {
                Showmesager.showmess(parent, "Sinh viên đã được xóa +)", "Thông báo");
            }
        } catch (Exception e2) {
            e2.printStackTrace();
            Showmesager.showerormess(parent, e2.getMessage(), "Lỗi");
        }
    }//GEN-LAST:event_btxoaActionPerformed

    private void btnhapmoiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnhapmoiActionPerformed
        txtmasosinhvien.setText("");
        txthoten.setText("");
        txtemail.setText("");
        txtsdt.setText("");
        txtarea.setText("");
    }//GEN-LAST:event_btnhapmoiActionPerformed

    private void btsuaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btsuaActionPerformed
        StringBuilder sb = new StringBuilder();
        Value.vl(txtmasosinhvien, sb, "Mã số sinh viên không được để trống !");
        Value.vl(txthoten, sb, "Họ và tên sinh viên không được để trống !");
        if (sb.length() > 0) {
            Showmesager.showerormess(parent, sb.toString(), "Lỗi");
            return;
        }
        if (Showmesager.showcomfirmess(parent, "Bạn có muốn cập nhật sinh viên không ",
                "Hỏi") == JOptionPane.NO_OPTION) {
            return;
        }
        try {
            hocsinh sv = new hocsinh();
            sv.setMaSinhVien(txtmasosinhvien.getText());
            sv.setHoTen(txthoten.getText());
            sv.setEmail(txtemail.getText());
            sv.setSDT(txtsdt.getText());
            sv.setGioiTinh(rdinam.isSelected() ? 1 : 0);
            sv.setDiaChi(txtarea.getText());
            sinhviendao dao = new sinhviendao();
            if (dao.update(sv)) {
                Showmesager.showmess(parent, "Sinh viên đã được cập nhật +)", "Thông báo");
            } else {
                Showmesager.showcomfirmess(parent, "Sinh viên không cập nhật được do lỗi kỹ thuật +(",
                        "Cảnh báo !!!");
            }
        } catch (Exception e2) {
            e2.printStackTrace();
            Showmesager.showerormess(parent, e2.getMessage(), "Lỗi");
        }
    }//GEN-LAST:event_btsuaActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnhapmoi;
    private javax.swing.JButton btsua;
    private javax.swing.JButton btthem;
    private javax.swing.JButton btxoa;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTable jTable1;
    private javax.swing.JRadioButton rdinam;
    private javax.swing.JRadioButton rdonu;
    private javax.swing.JTextArea txtarea;
    private javax.swing.JTextField txtemail;
    private javax.swing.JTextField txthoten;
    private javax.swing.JTextField txtmasosinhvien;
    private javax.swing.JTextField txtsdt;
    // End of variables declaration//GEN-END:variables
}
